const s = 16; // the side length of a single tile

const level = [
  { x: 0, y: s * 8 + 1, tile: new Tile() },
  { x: 1 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 2 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 3 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 4 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 5 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 6 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 7 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 8 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 9 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 10 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 11 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 12 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 13 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 14 * s + 1, y: s * 8 + 1, tile: new Tile() },
  { x: 15 * s + 1, y: s * 7 + 1, tile: new Tile() },
  { x: 16 * s + 1, y: s * 7 + 1, tile: new Tile() },
  { x: 17 * s + 1, y: s * 7 + 1, tile: new Tile() },
  { x: 18 * s + 1, y: s * 7 + 1, tile: new Tile() },
  { x: 19 * s + 1, y: s * 7 + 1, tile: new Tile() },
  { x: 20 * s + 1, y: s * 7 + 1, tile: new Tile() },
];
